// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz2FW03UwNZddz8Ei9_I4uAymdsHBX81o',
    appId: '1:836776250601:web:b86410eb03a130d2537478',
    messagingSenderId: '836776250601',
    projectId: 'care4u-medical-booking',
    authDomain: 'care4u-medical-booking.firebaseapp.com',
    storageBucket: 'care4u-medical-booking.firebasestorage.app',
    measurementId: 'G-QD7G56SP23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPwvh75r3u3V6OGsdJGaJAmwOlSUxV1pc',
    appId: '1:836776250601:android:2b174cf6dc338f65537478',
    messagingSenderId: '836776250601',
    projectId: 'care4u-medical-booking',
    storageBucket: 'care4u-medical-booking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAhmo4m5yI8d6a1j4Xp-NOvX0QrxBS4wU',
    appId: '1:836776250601:ios:6cf6cb836eed5dee537478',
    messagingSenderId: '836776250601',
    projectId: 'care4u-medical-booking',
    storageBucket: 'care4u-medical-booking.firebasestorage.app',
    iosBundleId: 'com.example.care4uMedicalBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAhmo4m5yI8d6a1j4Xp-NOvX0QrxBS4wU',
    appId: '1:836776250601:ios:6cf6cb836eed5dee537478',
    messagingSenderId: '836776250601',
    projectId: 'care4u-medical-booking',
    storageBucket: 'care4u-medical-booking.firebasestorage.app',
    iosBundleId: 'com.example.care4uMedicalBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz2FW03UwNZddz8Ei9_I4uAymdsHBX81o',
    appId: '1:836776250601:web:d4f862fbf85ebf00537478',
    messagingSenderId: '836776250601',
    projectId: 'care4u-medical-booking',
    authDomain: 'care4u-medical-booking.firebaseapp.com',
    storageBucket: 'care4u-medical-booking.firebasestorage.app',
    measurementId: 'G-M3Y3CFYPR8',
  );
}
